export interface TopicPreset {
  id: string;
  category: 'iFood & Taxas' | 'Vendas nos Dias Fracos' | 'Botão Impulsionar' | 'Retenção & WhatsApp' | 'Escala de Pedidos';
  title: string;
  targetCategory: string;
  painHook: string;
  recommendedTheme: 'dark_fire' | 'clean_authority' | 'alert_loss' | 'data_growth' | 'thread_social' | 'sunset_gradient';
}

export const TOPIC_PRESETS: TopicPreset[] = [
  {
    id: 'ifood-taxa-30',
    category: 'iFood & Taxas',
    title: 'O iFood está ficando com 27% a 30% do seu faturamento bruto?',
    targetCategory: 'Restaurantes e Deliveries em Geral',
    painHook: 'Você trabalha a noite inteira, gerencia a cozinha no calor, e no fim do mês 30% do seu lucro vai para o aplicativo.',
    recommendedTheme: 'alert_loss',
  },
  {
    id: 'terca-feira-morta',
    category: 'Vendas nos Dias Fracos',
    title: 'Por que seu delivery fatura no sábado, mas passa fome na terça-feira?',
    targetCategory: 'Hamburguerias e Pizzarias',
    painHook: 'Motoboys sentados no celular e chapa vazia toda terça e quarta. Isso não é falta de demanda na sua cidade, é falta de campanha programada.',
    recommendedTheme: 'dark_fire',
  },
  {
    id: 'botao-impulsionar-cilada',
    category: 'Botão Impulsionar',
    title: 'O erro de R$ 5.000 no botão "Impulsionar" do Instagram',
    targetCategory: 'Donos de Delivery',
    painHook: 'Você aperta impulsionar, ganha 50 curtidas de gente que mora a 30km de distância e zero pedidos no cardápio.',
    recommendedTheme: 'data_growth',
  },
  {
    id: 'whatsapp-proprio',
    category: 'Retenção & WhatsApp',
    title: 'Como transformar cada cliente do iFood em um cliente do seu canal próprio',
    targetCategory: 'Pizzarias, Açaí e Marmitarias',
    painHook: 'Pagar comissão duas vezes pelo mesmo cliente é o maior veneno para o caixa de qualquer food service.',
    recommendedTheme: 'thread_social',
  },
  {
    id: 'raio-de-entrega-geo',
    category: 'Escala de Pedidos',
    title: 'Tráfego Hiperlocal: Anuncie apenas para quem está a 15 minutos do seu restaurante',
    targetCategory: 'Hamburguerias e Sushis',
    painHook: 'Mostre seu burger suculento exatamente no horário da fome (18h às 21h) para quem está no raio de entrega da sua frota.',
    recommendedTheme: 'sunset_gradient',
  },
  {
    id: 'margem-liquida-lucro',
    category: 'iFood & Taxas',
    title: 'Vender R$ 50 mil e sobrar R$ 3 mil: A armadilha do delivery sem canal próprio',
    targetCategory: 'Food Service Geral',
    painHook: 'Volume de vendas não é dinheiro no bolso. Sem tráfego direto para o seu cardápio, você está apenas trabalhando de funcionário do aplicativo.',
    recommendedTheme: 'alert_loss',
  },
  {
    id: 'motoboy-parado',
    category: 'Vendas nos Dias Fracos',
    title: 'Como manter sua cozinha operando no ritmo de sexta-feira todos os dias',
    targetCategory: 'Pizzarias e Hamburguerias',
    painHook: 'Crie picos de pedidos previsíveis com ofertas de meio de semana disparadas via anúncios para sua base de clientes locais.',
    recommendedTheme: 'clean_authority',
  },
  {
    id: 'pixel-cardapio-digital',
    category: 'Escala de Pedidos',
    title: 'Por que seu cardápio digital está acumulando poeira virtual?',
    targetCategory: 'Restaurantes e Bares',
    painHook: 'Contratar um cardápio digital e não fazer tráfego pago é o mesmo que abrir um restaurante no subsolo sem placa na porta.',
    recommendedTheme: 'dark_fire',
  },
];

export const THEME_CONFIGS = {
  dark_fire: {
    id: 'dark_fire',
    name: 'Dark Fire (Assinatura)',
    tag: 'Recomendado',
    bg: '#0a0a0a',
    cardBg: '#141414',
    cardBorder: 'rgba(255, 61, 0, 0.25)',
    accent: '#FF3D00',
    accentGradient: 'linear-gradient(135deg, #FF3D00 0%, #EA580C 100%)',
    textColor: '#FFFFFF',
    textMuted: '#A1A1AA',
    badgeBg: 'rgba(255, 61, 0, 0.15)',
    badgeBorder: 'rgba(255, 61, 0, 0.4)',
    badgeText: '#FF3D00',
    description: 'Fundo preto profundo com laranja fogo incandescente. Visual moderno de alta agência.',
  },
  clean_authority: {
    id: 'clean_authority',
    name: 'Clean Authority',
    tag: 'Corporativo',
    bg: '#F8F9FA',
    cardBg: '#FFFFFF',
    cardBorder: '#E5E7EB',
    accent: '#EA580C',
    accentGradient: 'linear-gradient(135deg, #EA580C 0%, #C2410C 100%)',
    textColor: '#0F172A',
    textMuted: '#64748B',
    badgeBg: '#FFF7ED',
    badgeBorder: '#FDBA74',
    badgeText: '#EA580C',
    description: 'Fundo claro editorial de alto contraste. Passa autoridade e clareza imediata.',
  },
  alert_loss: {
    id: 'alert_loss',
    name: 'Alerta de Prejuízo',
    tag: 'Máximo Choque',
    bg: '#0B0B0C',
    cardBg: '#181111',
    cardBorder: 'rgba(239, 68, 68, 0.35)',
    accent: '#FF2E2E',
    accentGradient: 'linear-gradient(135deg, #FF2E2E 0%, #FF5A1F 100%)',
    textColor: '#FFFFFF',
    textMuted: '#CBD5E1',
    badgeBg: 'rgba(239, 68, 68, 0.2)',
    badgeBorder: 'rgba(239, 68, 68, 0.5)',
    badgeText: '#FF5A5A',
    description: 'Impacto visual dramático para apontar onde o dono do restaurante está perdendo dinheiro.',
  },
  data_growth: {
    id: 'data_growth',
    name: 'Data & Growth',
    tag: 'Métricas ROI',
    bg: '#090D14',
    cardBg: '#111827',
    cardBorder: 'rgba(255, 61, 0, 0.25)',
    accent: '#FF3D00',
    accentGradient: 'linear-gradient(135deg, #FF3D00 0%, #3B82F6 100%)',
    textColor: '#F8FAFC',
    textMuted: '#94A3B8',
    badgeBg: 'rgba(30, 41, 59, 0.8)',
    badgeBorder: 'rgba(255, 61, 0, 0.3)',
    badgeText: '#FF7A50',
    description: 'Estilo dashboard com foco em números, taxa de comissão reduzida e faturamento.',
  },
  thread_social: {
    id: 'thread_social',
    name: 'Thread & Perfil',
    tag: 'Bate-papo B2B',
    bg: '#0D0E12',
    cardBg: '#161922',
    cardBorder: 'rgba(255, 255, 255, 0.1)',
    accent: '#FF4D15',
    accentGradient: 'linear-gradient(135deg, #FF4D15 0%, #FFA133 100%)',
    textColor: '#FFFFFF',
    textMuted: '#9CA3AF',
    badgeBg: 'rgba(255, 77, 21, 0.15)',
    badgeBorder: 'rgba(255, 77, 21, 0.3)',
    badgeText: '#FF4D15',
    description: 'Formato conversa direta/thread. Parece um conselho valioso entre donos de negócios.',
  },
  sunset_gradient: {
    id: 'sunset_gradient',
    name: 'Sunset Food',
    tag: 'Gastronômico',
    bg: '#08080A',
    cardBg: 'linear-gradient(180deg, rgba(25, 15, 10, 0.9) 0%, rgba(12, 12, 15, 0.95) 100%)',
    cardBorder: 'rgba(234, 88, 12, 0.3)',
    accent: '#F97316',
    accentGradient: 'linear-gradient(135deg, #EA580C 0%, #F59E0B 100%)',
    textColor: '#FFFFFF',
    textMuted: '#E2E8F0',
    badgeBg: 'rgba(234, 88, 12, 0.2)',
    badgeBorder: 'rgba(249, 115, 22, 0.4)',
    badgeText: '#FDBA74',
    description: 'Gradiente quente e apetitoso. Estimula a atmosfera de comida e pedidos em alta.',
  },
};
